import 'bootstrap/js/dist/collapse';
import 'bootstrap/js/dist/util';
import 'bootstrap/js/dist/modal';
import 'bootstrap/js/dist/tab';
import 'magnific-popup';
import './src/scss/index.scss';
import './src/js/msopGallery';
import './src/js/app';
import './src/js/msProductContentDynamic';
